# Generated by Django 4.0.4 on 2022-06-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_title',
        ),
    ]
